name: Create new release

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install fuse libfuse2
      run: sudo apt install fuse libfuse2

    - name: Make balenaEtcher AppDir
      run: |
        set -x
        version=$(grep -o "balenaEtcher:.*" README.md | cut -d ' ' -f2)
        echo "balenaEtcher version: $version"

        mkdir -p balenaEtcher.AppDir/

        #cp balenaEtcher.desktop balenaEtcher.AppDir/

        cat > balenaEtcher.AppDir/balenaEtcher.desktop << 'EOF'
        [Desktop Entry]
        Name=balenaEtcher
        Exec=balena-etcher
        Icon=balenaEtcher
        Terminal=false
        Type=Application
        Categories=Utility;
        EOF

        chmod +x balenaEtcher.AppDir/balenaEtcher.desktop

        cat > balenaEtcher.AppDir/AppRun << 'EOF'
        #!/bin/bash
        HERE="$(dirname "$(readlink -f "${0}")")"

        cd /"$HERE"/usr/bin/
        echo -e "\n/"$HERE"/usr/bin/balena-etcher $@\n"
        ./balena-etcher $@
        EOF

        chmod +x balenaEtcher.AppDir/AppRun

        mkdir -p balenaEtcher.AppDir/usr/
        cd balenaEtcher.AppDir/usr/

        wget https://github.com/balena-io/etcher/releases/download/v$version/balenaEtcher-linux-x64-$version.zip
        unzip balenaEtcher-linux-x64-$version.zip
        rm balenaEtcher-linux-x64-$version.zip
        mv balenaEtcher-linux-x64/ bin/

        pwd
        ls -lah
        cd ../../
        pwd
        ls -lah

        wget https://github.com/balena-io/etcher/blob/master/assets/iconset/128x128.png -O balenaEtcher.AppDir/balenaEtcher.png
        cp README.md balenaEtcher.AppDir

    - name: Get appimagetool
      run: |
        set -x
        #wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        version_go_appimage=$(wget -q -O - https://api.github.com/repos/probonopd/go-appimage/releases | grep "\"name.*appimagetool-.*-x86_64.AppImage\"" | head -n 1 | cut -d '-' -f2)
        echo "version_go_appimage: $version_go_appimage"

        wget -q "https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-$version_go_appimage-x86_64.AppImage" -O appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

    - name: Make AppImage
      run:  |
        set -x
        pwd; ls -lah
        version=$(grep -o "balenaEtcher:.*" README.md | cut -d ' ' -f2)
        echo "balenaEtcher version: $version"

        ARCH=x86_64 VERSION="${version}-1_JB" ./appimagetool-x86_64.AppImage balenaEtcher.AppDir

        fileName=$(ls balenaEtcher*.AppImage)
        echo "fileName: $fileName"

        md5sum "$fileName" > "${fileName}.md5"
        pwd; ls -lah

    # Build - Errror: Resource not accessible by integration
    # Change Settings -> Actions -> General -> Workflow Permissions to allow read and write:
    # https://github.com/actions/first-interaction/issues/10#issuecomment-1506118886

    # https://github.com/marketplace/actions/upload-to-github-release
    - uses: xresloader/upload-to-github-release@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "balenaEtcher*.AppImage; balenaEtcher*.zsync ; balenaEtcher*.md5"
          #delete_file: "random-name-*.txt;random-*.txt"
          release_id: ${{ steps.create_release.outputs.id }}
          #overwrite: true
          verbose: true
          #tags: true
          draft: false
          default_release_name: "balenaEtcher V in AppImage"
